# Generated by Django 5.0.2 on 2024-07-31 14:47

import datetime

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=datetime.datetime.today,
                        unique=True,
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название"),
                ),
            ],
            options={
                "verbose_name": "поставка",
                "verbose_name_plural": "поставки ⬆️",
            },
        ),
        migrations.CreateModel(
            name="WriteOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=datetime.datetime.today,
                        unique=True,
                        verbose_name="Дата создания",
                    ),
                ),
            ],
            options={
                "verbose_name": "списание",
                "verbose_name_plural": "списания ⬇️",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "units",
                    models.CharField(
                        default="шт", verbose_name="Единица измерения"
                    ),
                ),
            ],
            options={
                "verbose_name": "товар",
                "verbose_name_plural": "товары 📦",
                "unique_together": {("name", "description")},
            },
        ),
        migrations.CreateModel(
            name="ItemDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0)
                        ],
                        verbose_name="Количество",
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_delivery",
                        to="stock.delivery",
                        verbose_name="товар",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_item",
                        to="stock.product",
                        verbose_name="товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "строка",
                "verbose_name_plural": "строки",
                "unique_together": {("delivery", "product")},
            },
        ),
        migrations.CreateModel(
            name="ItemWriteOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="Количество")),
                (
                    "product",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_item",
                        to="stock.product",
                        verbose_name="товар",
                    ),
                ),
                (
                    "write_off",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_write_off",
                        to="stock.writeoff",
                        verbose_name="товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "строка",
                "verbose_name_plural": "строки",
                "unique_together": {("write_off", "product")},
            },
        ),
    ]
