# Generated by Django 5.0.2 on 2024-07-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="minimum_balance",
            field=models.IntegerField(
                default=1, verbose_name="Минимальный остаток"
            ),
        ),
    ]
