# Generated by Django 5.0.2 on 2024-08-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0002_product_minimum_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="is_shipped",
            field=models.BooleanField(default=False, verbose_name="Отгружена"),
        ),
    ]
