# Generated by Django 5.0.2 on 2024-09-22 11:27

import datetime

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0003_delivery_is_shipped"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime.today,
                unique=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="writeoff",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime.today,
                unique=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Дата создания",
            ),
        ),
    ]
