# Generated by Django 5.0.2 on 2024-09-22 12:51

import datetime

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0004_alter_delivery_date_alter_writeoff_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="delivery",
            name="name",
        ),
        migrations.AlterField(
            model_name="delivery",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime.today,
                unique=True,
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="itemwriteoff",
            name="quantity",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Количество",
            ),
        ),
        migrations.AlterField(
            model_name="writeoff",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime.today,
                unique=True,
                verbose_name="Дата создания",
            ),
        ),
    ]
