# Generated by Django 5.0.2 on 2024-09-22 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0005_remove_delivery_name_alter_delivery_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemdelivery",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_item",
                to="stock.product",
                verbose_name="товар",
            ),
        ),
        migrations.AlterField(
            model_name="itemwriteoff",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_item",
                to="stock.product",
                verbose_name="товар",
            ),
        ),
    ]
