# Generated by Django 5.0.2 on 2024-07-09 09:13

import datetime
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import salary.models
import utils
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(verbose_name="Название")),
                (
                    "description",
                    models.CharField(
                        blank=True, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
                ("file_data", models.BinaryField(null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Шаблон активен"
                    ),
                ),
            ],
            options={
                "verbose_name": "шаблон",
                "verbose_name_plural": "шаблоны договоров",
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_signed",
                    models.BooleanField(
                        default=False, verbose_name="Оригинал подписан"
                    ),
                ),
                (
                    "number",
                    models.IntegerField(
                        default=salary.models.get_new_contract_number,
                        unique=True,
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name="Номер договора",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=datetime.datetime.today,
                        verbose_name="Дата заключения договора",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Дата окончания договора",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="сontract",
                        to="core.employee",
                        verbose_name="Сотрудник",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="сontract",
                        to="salary.contracttemplate",
                        verbose_name="Шаблон договора",
                    ),
                ),
            ],
            options={
                "verbose_name": "договор",
                "verbose_name_plural": "договоры",
                "unique_together": {("employee", "template")},
            },
        ),
        migrations.CreateModel(
            name="HourlyPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(verbose_name="Название")),
                (
                    "value",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0)
                        ],
                    ),
                ),
                (
                    "contract",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hourly_payment",
                        to="salary.contracttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Правило: Почасовая ставка",
            },
        ),
        migrations.CreateModel(
            name="PercentageOfSales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(verbose_name="Название")),
                (
                    "percentage_value",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0"),
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "contract",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="percentage_of_sales",
                        to="salary.contracttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Правило: Процент от личных продаж",
            },
        ),
        migrations.CreateModel(
            name="Rate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(verbose_name="Название")),
                (
                    "value",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0)
                        ],
                        verbose_name="Сумма",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate",
                        to="salary.contracttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "ставка",
                "verbose_name_plural": "Правило: Ставка",
            },
        ),
        migrations.CreateModel(
            name="SalaryCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.IntegerField(
                        default=salary.models.get_new_salary_certificate_number,
                        unique=True,
                        verbose_name="Номер документа",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=utils.first_day_of_the_previous_month,
                        verbose_name="Начало отчётного периода",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        default=utils.last_day_of_the_previous_month,
                        verbose_name="Конец отчётного периода",
                    ),
                ),
                (
                    "date_of_creation",
                    models.DateField(
                        default=datetime.datetime.today,
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "original_signed",
                    models.BooleanField(
                        default=False, verbose_name="Оригинал подписан"
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_certificate",
                        to="salary.contract",
                        verbose_name="договор",
                    ),
                ),
            ],
            options={
                "verbose_name": "зарплатный акт",
                "verbose_name_plural": "зарплатные акты",
            },
        ),
        migrations.CreateModel(
            name="AmountOfAccrual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "required_field",
                    models.CharField(
                        blank=True, null=True, verbose_name="Обязательное поле"
                    ),
                ),
                (
                    "value",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0)
                        ],
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amount_of_accrual",
                        to="salary.contracttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сумма начислений",
                "verbose_name_plural": "Правило: Сумма начислений",
                "unique_together": {("required_field", "contract")},
            },
        ),
    ]
