# Generated by Django 5.0.2 on 2024-07-31 14:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("salary", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rate",
            unique_together={("name", "contract")},
        ),
    ]
