# Generated by Django 5.0.2 on 2024-08-12 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("salary", "0002_alter_rate_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="salarycertificate",
            name="is_blocked",
            field=models.BooleanField(
                default=False, verbose_name="Редактирование не доступно"
            ),
        ),
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(verbose_name="Название")),
                ("price", models.FloatField(verbose_name="Цена")),
                (
                    "count",
                    models.FloatField(default=0, verbose_name="Колл-во"),
                ),
                ("unit", models.CharField(default="шт.", verbose_name="Ед.")),
                (
                    "is_auto",
                    models.BooleanField(
                        default=False, verbose_name="Автоматическое поле"
                    ),
                ),
                (
                    "salary_certificate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field",
                        to="salary.salarycertificate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Строка",
                "verbose_name_plural": "Строки",
                "unique_together": {("name", "salary_certificate")},
            },
        ),
    ]
