# Generated by Django 5.0.2 on 2024-08-12 20:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("salary", "0003_salarycertificate_is_blocked_field"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="field",
            unique_together={("name", "salary_certificate", "is_auto")},
        ),
    ]
