# Generated by Django 5.0.2 on 2024-11-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("salary", "0004_alter_field_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="salarycertificate",
            name="have_receipt",
            field=models.BooleanField(default=False, verbose_name="Есть чек"),
        ),
    ]
