# Generated by Django 5.0.2 on 2024-07-09 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accrual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="Дата начисления")),
                (
                    "name",
                    models.CharField(
                        blank=True, null=True, verbose_name="Название"
                    ),
                ),
                (
                    "base",
                    models.CharField(
                        blank=True, null=True, verbose_name="Основание"
                    ),
                ),
                ("sum", models.FloatField(verbose_name="Сумма")),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accrual",
                        to="core.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "начисление",
                "verbose_name_plural": "начисления",
                "unique_together": {
                    ("date", "employee", "name", "base", "sum")
                },
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="Дата оплаты")),
                (
                    "client",
                    models.CharField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Клиент",
                    ),
                ),
                ("sum", models.FloatField(verbose_name="Сумма")),
                (
                    "name",
                    models.CharField(
                        blank=True, null=True, verbose_name="Название"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sale",
                        to="core.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продажа",
                "verbose_name_plural": "Продажи",
                "unique_together": {
                    ("date", "employee", "name", "sum", "client")
                },
            },
        ),
    ]
