# Generated by Django 5.0.2 on 2024-07-09 09:13

import core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Default",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "work_time",
                    models.FloatField(
                        verbose_name="Рабочее время по умолчанию"
                    ),
                ),
                (
                    "planning_horizon",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1)
                        ],
                        verbose_name="Горизонт планирования (дни)",
                    ),
                ),
                (
                    "cashier_telegram_id",
                    models.CharField(verbose_name="Telegram id для чеков"),
                ),
            ],
            options={
                "verbose_name": "настройка",
                "verbose_name_plural": "настройки",
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "surname",
                    models.CharField(
                        blank=True, null=True, verbose_name="Фамилия"
                    ),
                ),
                ("name", models.CharField(verbose_name="Имя")),
                (
                    "patronymic",
                    models.CharField(
                        blank=True, null=True, verbose_name="Отчество"
                    ),
                ),
                (
                    "inn",
                    models.CharField(
                        blank=True,
                        help_text="10 или 12 цифр",
                        max_length=12,
                        null=True,
                        unique=True,
                        verbose_name="ИНН",
                    ),
                ),
                (
                    "tax_registration_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Дата регистрации в качестве плательщика НПД",
                    ),
                ),
                (
                    "tax_regime",
                    models.CharField(
                        choices=[
                            ("ИП", "Индивидуальный предприниматель"),
                            ("СЗ", "Самозанятый"),
                        ],
                        default="СЗ",
                        verbose_name="Режим налогообложения",
                    ),
                ),
                (
                    "ogrnip",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="14 цифр",
                        max_digits=20,
                        null=True,
                        unique=True,
                        verbose_name="ОГРНИП",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        null=True,
                        verbose_name="Адрес, как в паспорте",
                    ),
                ),
                (
                    "checking_account",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=20,
                        null=True,
                        unique=True,
                        verbose_name="Номер счёта",
                    ),
                ),
                (
                    "bank",
                    models.CharField(
                        blank=True,
                        help_text="ПАО ВТБ",
                        null=True,
                        verbose_name="Название банка",
                    ),
                ),
                (
                    "bik",
                    models.CharField(
                        blank=True,
                        help_text="9 цифр",
                        null=True,
                        verbose_name="БИК",
                    ),
                ),
                (
                    "correspondent_account",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=20,
                        null=True,
                        verbose_name="Кор. счёт",
                    ),
                ),
                (
                    "passport_series",
                    models.CharField(
                        blank=True,
                        help_text="4520 (4 цифр)",
                        max_length=4,
                        null=True,
                        validators=[core.validators.passport_series_validator],
                        verbose_name="Серия паспорта",
                    ),
                ),
                (
                    "passport_number",
                    models.CharField(
                        blank=True,
                        help_text="123342 (6 цифр)",
                        max_length=6,
                        null=True,
                        verbose_name="Номер паспорта",
                    ),
                ),
                (
                    "issued_by",
                    models.CharField(
                        blank=True, null=True, verbose_name="Кем выдан"
                    ),
                ),
                (
                    "date_of_issue",
                    models.DateField(
                        blank=True,
                        null=True,
                        validators=[core.validators.exclude_future_dates],
                        verbose_name="Дата выдачи",
                    ),
                ),
                (
                    "department_code",
                    models.CharField(
                        blank=True,
                        help_text="660003 (6 цифр)",
                        max_length=6,
                        null=True,
                        verbose_name="Код подразделения",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True,
                        help_text="john.smith@example.com",
                        null=True,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "telegram_id",
                    models.CharField(
                        blank=True,
                        help_text="1234567890 (10 цифр)",
                        null=True,
                        unique=True,
                        verbose_name="Telegram id",
                    ),
                ),
                (
                    "gdpr_is_signed",
                    models.BooleanField(
                        default=False, verbose_name="Обработка ПД"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Сотрудник активен"
                    ),
                ),
                (
                    "is_stuff",
                    models.BooleanField(
                        default=False, verbose_name="Права суперпользователя"
                    ),
                ),
                (
                    "is_owner",
                    models.BooleanField(
                        default=False, verbose_name="Владелец"
                    ),
                ),
            ],
            options={
                "verbose_name": "сотрудник",
                "verbose_name_plural": "сотрудники",
            },
        ),
        migrations.CreateModel(
            name="BotRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_id",
                    models.CharField(unique=True, verbose_name="Telegram id"),
                ),
                ("username", models.CharField(verbose_name="username")),
                (
                    "first_name",
                    models.CharField(
                        blank=True, null=True, verbose_name="Имя"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, null=True, verbose_name="Фамилия"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot_request",
                        to="core.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "запрос",
                "verbose_name_plural": "запросы пользователей",
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "time",
                    models.FloatField(
                        default=11.5, verbose_name="Рабочее время"
                    ),
                ),
                (
                    "second_employee",
                    models.BooleanField(
                        default=False, verbose_name="Второй сотрудник на смене"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule",
                        to="core.employee",
                        verbose_name="Сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "запись",
                "verbose_name_plural": "рабочий график",
                "unique_together": {("date", "second_employee")},
            },
        ),
    ]
