# Generated by Django 5.0.2 on 2024-07-24 11:30

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="+7985123456",
                max_length=13,
                validators=[core.validators.phone_validater],
                verbose_name="Номер телефона",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="time",
            field=models.FloatField(
                default=None, verbose_name="Рабочее время"
            ),
        ),
    ]
