# Generated by Django 5.0.2 on 2024-07-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_employee_phone_alter_schedule_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="time",
            field=models.FloatField(
                default=11.5, verbose_name="Рабочее время"
            ),
        ),
    ]
