# Generated by Django 5.0.2 on 2024-10-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_schedule_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="is_manager",
            field=models.BooleanField(
                default=False, verbose_name="Права управляющего"
            ),
        ),
    ]
